// Screen support
#define ST7789_NUM_DEVICES 1
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
#define LCD_RST_PIN NO_PIN
#define LCD_DC_PIN GP29
#define LCD_CS_PIN GP5
#define LCD_SPI_DIVISOR 8
#define QUANTUM_PAINTER_DEBUG
#define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS true

#define BACKLIGHT_PIN GP28

// Cirque support, comment out if using two screens
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define AZOTEQ_IQS5XX_TPS65
#define POINTING_DEVICE_ROTATION_90
#define WHEEL_EXTENDED_REPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE true
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 20
