ENCODER_MAP_ENABLE = yes
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
POINTING_DEVICE_DRIVER = azoteq_iqs5xx
POINTING_DEVICE_ENABLE = yes
BACKLIGHT_ENABLE = yes
BACKLIGHT_DRIVER = software